added iot_analytics
GoogleCloudPlatform/dataflow-solution-guides pull request #59
Opened 2024-10-14 06:50 UTC by paraschavda2411

Not sure about the terraform code, Its just a copy paste
pipeline code is working and tested locally. please do let me know if there are any changes needed in code and readme as well

2024-12-02 04:52 UTC, paraschavda2411 commented
Added some fix on terraform and updated the readme

2025-01-01 22:02 UTC, iht commented
Hi @paraschavda2411, thanks for sending the additional fixes.

The Terraform code is not passing the automated build. Please check the details given in the [CONTRIBUTING.md](https://github.com/GoogleCloudPlatform/dataflow-solution-guides/blob/main/CONTRIBUTING.md) file to run the checks locally and fix any issues (formatting issues can be fixed automatically).

For the Python pipeline, the `setup.py` file is missing. Please see other Python pipelines as an example on how to structure the Python pipeline for the solution guides. The CONTRIBUTING.md file also gives a couple of commands to automatically reformat your code and check any issues, if that would be necessary. The automated tests will not be triggered until you submit a `setup.py` file with your pipeline.

2025-01-07 20:04 UTC, iht requested changes

2025-01-18 10:56 UTC, paraschavda2411 commented on terraform/iot_analytics/main.tf
> +}
Formatted the code

2025-01-18 10:56 UTC, paraschavda2411 commented on pipelines/iot_analytics/pipeline/__init__.py
> +#  Copyright 2023 Google LLC
updated the years in each file

2025-01-18 10:56 UTC, paraschavda2411 commented on pipelines/iot_analytics/pipeline/setup.py
> +    name='transformations',
Added descriptive name

2025-01-18 10:57 UTC, paraschavda2411 commented on pipelines/iot_analytics/pipeline/create_publish_and_model_files/create_and_populate_bigtable.py
> +# Create Bigtable Data (Weather data) and Load Records
Added license headers in all files

2025-01-18 10:57 UTC, paraschavda2411 commented on pipelines/iot_analytics/pipeline/create_publish_and_model_files/create_and_populate_bigtable.py
> +TABLE_ID = 'maintenance_data'
updated the files according to pylint specs

2025-01-18 16:44 UTC, iht requested changes
Please see the comments for some additional changes. They are about some .DS_store files that should not be in the repo, and about the TF code and documentation.

Also, please make all the variables in the TF code optional (e.g. by providing default values), except the variables `project_create`, `project_id` and `region`.

There is a manual TF build that tries to deploy your code in some testing infra that assumes that all the variables have default values, except those three. See the build result at https://github.com/GoogleCloudPlatform/dataflow-solution-guides/actions/runs/12845729867/job/35820111293#step:7:2963

Thanks again for sending all these changes. Looking forward to these final changes to get this PR merged.

2025-01-18 16:44 UTC, iht commented on .DS_Store
Remove this file

2025-01-18 16:44 UTC, iht commented on pipelines/.DS_Store
Remove this file

2025-01-18 16:44 UTC, iht commented on pipelines/iot_analytics/.DS_Store
Remove this file

2025-01-18 16:44 UTC, iht commented on pipelines/iot_analytics/iot_analytics_pipeline/.DS_Store
Remove this file

2025-01-18 16:44 UTC, iht commented on pipelines/iot_analytics/scripts/00_set_environment.sh
> +export PROJECT_ID=learnings-421714
Please remove this file from the PR. This file is generated by the Terraform code (see the main.tf file, last part of the file). If not all variables are set in the Terraform code, please include them in the Terraform code.

2025-01-18 16:44 UTC, iht commented on terraform/iot_analytics/README.md
> +
Please update this file to make sure it matches this solution guide. The content seems to be mixed with other solution guides.

2025-01-18 16:44 UTC, iht commented on terraform/iot_analytics/main.tf
> +}
Make sure that all the variables that are required in the `scripts/00_set_environment.sh` file are actually generated here. Also, change the script name here or in the docs, so it is consistent across this solution guide. It  is called `00_set_variables.sh` here in the `main.tf` file.

2025-01-20 08:38 UTC, paraschavda2411 commented on pipelines/iot_analytics/iot_analytics_pipeline/.DS_Store
Done

2025-01-20 08:38 UTC, paraschavda2411 commented on pipelines/iot_analytics/.DS_Store
Done

2025-01-20 08:38 UTC, paraschavda2411 commented on pipelines/.DS_Store
Done

2025-01-20 08:38 UTC, paraschavda2411 commented on terraform/iot_analytics/main.tf
> +}
Updated

2025-01-21 11:14 UTC, iht commented on terraform/iot_analytics/variables.tf
> +}
Please add a default value for this property. The automated deploy test needs a value for that property (https://github.com/GoogleCloudPlatform/dataflow-solution-guides/actions/runs/12885707573/job/35924732784).

The only properties with no default values should be `project_id`, ` region` and `project_create`.

2025-01-21 11:14 UTC, iht requested changes
Almost there, please add a default value for one of the TF variables, so the deploy build does not fail (https://github.com/GoogleCloudPlatform/dataflow-solution-guides/actions/runs/12885707573/job/35924732784)

2025-01-21 13:04 UTC, iht commented
Manual deploy build passing! https://github.com/GoogleCloudPlatform/dataflow-solution-guides/actions/runs/12887532595/job/35930424260

2025-01-21 13:04 UTC, iht approved these changes
Thanks for this contribution to the repo!

2025-01-21 13:04 UTC, merged