Add Ads Analytics Pipeline
GoogleCloudPlatform/dataflow-solution-guides pull request #64
Opened 2024-12-19 15:13 UTC by yamigil

Added the Ads_Analytics Pipeline

2025-01-01 22:12 UTC, iht commented
Hi @yamigil, 

Please remove all the `.DS_Store` files in this PR.

Your Java pipeline is using Maven, and the automated build and checks in this repo assume that Java pipelines use gradle. Adapting your code to using `gradle` should be easy, you need to copy some files and edit the names (package and class name in the `build.gradle` file, maybe some dependencies if you are using specific dependencies).

Alternatively, we could try adding support for Maven in the automated build too, but you would need to update your Maven settings to use `spotless` and  `errorprone`, so we apply the same validations as we do with gradle.

Please let me know what is your preferred choice (switch to Gradle or stay in Maven).

Thanks for sending this PR!

2025-01-07 20:04 UTC, iht requested changes

2025-01-07 21:20 UTC, yamigil commented
Let me change it to Gradle and get back to you

2025-04-24 16:30 UTC, yamigil commented
Hi Israel, the validation error I'm getting is not part of my pipeline:

```
Traceback (most recent call last):
  File "/home/runner/work/dataflow-solution-guides/dataflow-solution-guides/pipelines/cdp/setup.py", line 18, in <module>
    from setuptools import setup, find_packages
ModuleNotFoundError: No module named 'setuptools'
```

How can we get past it?

Thanks

2026-05-19 10:45 UTC, closed without merging

2026-05-19 10:45 UTC, iht commented
Closing as outdated, please reopen if you want to keep working on this contribution